# Generated by Django 4.2.7 on 2023-11-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_message_id', models.BigIntegerField(default=1, verbose_name='ID в телеграмме')),
                ('text', models.TextField(default='Empty', verbose_name='Текст сообщения')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('reactions', models.BigIntegerField(default=0, verbose_name='Реакции')),
                ('forwards', models.BigIntegerField(default=0, verbose_name='Репосты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('average_reaction_coef', models.DecimalField(decimal_places=2, default=1, help_text='Текущий коэффициент', max_digits=5, verbose_name='Коэффициент реакций')),
                ('average_forward_coef', models.DecimalField(decimal_places=2, default=1, help_text='Текущий коэффициент', max_digits=5, verbose_name='Коэффициент репостов')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Переслан?')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channel.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'unique_together': {('channel', 'tg_message_id')},
            },
        ),
    ]
