# Generated by Django 4.2.7 on 2023-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='average_forward_coef',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Текущий коэффициент', max_digits=5, verbose_name='Коэффициент репостов'),
        ),
        migrations.AlterField(
            model_name='message',
            name='average_reaction_coef',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Текущий коэффициент', max_digits=5, verbose_name='Коэффициент реакций'),
        ),
    ]
