# Generated by Django 4.2.7 on 2023-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_average_forward_coef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='average_forward_coef',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Текущий коэффициент', max_digits=10, verbose_name='Коэффициент репостов'),
        ),
        migrations.AlterField(
            model_name='message',
            name='average_reaction_coef',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Текущий коэффициент', max_digits=10, verbose_name='Коэффициент реакций'),
        ),
    ]
