# Generated by Django 4.2.7 on 2023-11-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.BigIntegerField(default=0, verbose_name='Просмотры')),
                ('reactions', models.BigIntegerField(default=0, verbose_name='Реакции')),
                ('forwards', models.BigIntegerField(default=0, verbose_name='Репосты')),
                ('reaction_coef', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Коэффициент реакций')),
                ('forwards_coef', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Коэффициент реакций')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='message.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
    ]
