# Generated by Django 4.2.7 on 2023-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='forwards_coef',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Коэффициент репостов'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='reaction_coef',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Коэффициент реакций'),
        ),
    ]
