# Generated by Django 4.2.7 on 2023-11-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_chat_id', models.CharField(help_text='ID чата, куда отправлять посты, превысившие кап', max_length=128, verbose_name='Id чата')),
                ('name', models.CharField(default='Без названия', max_length=128, verbose_name='Название категории чата')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='TG ID чата')),
                ('name', models.CharField(default='No name channel', max_length=128, verbose_name='Название канала')),
                ('average_react_coef', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Коэффициент, когда репостим по реакциям')),
                ('average_forward_coef', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Коэффициент, когда репостим по репостам')),
                ('is_tracking', models.BooleanField(default=False, verbose_name='Отслеживаем?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels', to='channel.category', verbose_name='Категория чата')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
