# Generated by Django 4.2.7 on 2023-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name channel', max_length=128, verbose_name='Название канала')),
                ('category', models.CharField(default='Без категории', help_text='Для фильтрации', max_length=128, verbose_name='Категория канала')),
                ('max_react_coef', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Если он None - берется из настроек', max_digits=5, null=True, verbose_name='Коэффициент, когда репостим по реакциям')),
                ('max_forward_coef', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Если он None - берется из настроек', max_digits=5, null=True, verbose_name='Коэффициент, когда репостим по репостам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
