# Generated by Django 4.2.7 on 2023-11-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_average_forward_coef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='average_forward_coef',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='Коэф. репоста'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='average_react_coef',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='Коэф. реакции'),
        ),
    ]
