# Generated by Django 4.2.7 on 2023-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_forward_coef', models.DecimalField(decimal_places=2, default=10, help_text='Коэффициент, выше которого репостим сообщение', max_digits=5, verbose_name='Коэффициент репостов')),
                ('max_reaction_coef', models.DecimalField(decimal_places=2, default=10, help_text='Коэффициент, выше которого репостим сообщение', max_digits=5, verbose_name='Коэффициент реакций')),
                ('additional_percents_for_repost', models.DecimalField(decimal_places=2, default=30, help_text='Процент превышения, при котором репостим (%)', max_digits=5, verbose_name='Процент превышения')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
