# Generated by Django 4.2.7 on 2023-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_percents_for_repost', models.DecimalField(decimal_places=2, default=30, help_text='Процент превышения, при котором репостим (%)', max_digits=5, verbose_name='Процент превышения')),
                ('starting_interval_second_task', models.IntegerField(choices=[(5, 5), (10, 10)], default=5, help_text='В минутах', verbose_name='Интервал запуска второй задачи')),
                ('min_messages_count_before_repost', models.IntegerField(default=20, help_text='Минимальное количество сообщений в канале до отправки репоста', verbose_name='Минимальное количество сообщений')),
                ('min_metrics_count_before_repost', models.IntegerField(default=5, help_text='Количество метрик у сообщения до отправки репоста', verbose_name='Количество метрик')),
                ('messages_ttl', models.IntegerField(default=30, help_text='В днях, метрики удаляются вместе. 0 - не удалять вообще никакие сообщения.', verbose_name='Длительность хранения сообщений')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
