# Generated by Django 4.2.7 on 2023-11-06 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsettings',
            name='views_div',
            field=models.IntegerField(default=100, help_text='rection coef = reactions / (views / знаменатель)', validators=[django.core.validators.MinValueValidator(0.1, message='Делитель должен быть строго больше 0')], verbose_name='Знаменатель для просмотров в формуле'),
        ),
    ]
