# Generated by Django 4.2.7 on 2023-11-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsettings',
            name='starting_interval_second_task',
            field=models.IntegerField(choices=[(5, 5), (10, 10)], default=5, help_text='В минутах', verbose_name='Интервал запуска второй задачи'),
        ),
    ]
