# Generated by Django 4.2.7 on 2023-11-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_parts', '0003_alter_externalsettings_additional_percents_for_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsettings',
            name='additional_percents_for_repost',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Процент превышения, при котором репостим (%)', max_digits=5, verbose_name='Процент превышения'),
        ),
    ]
